name: delphos-works
services:
- name: api
  source_dir: /
  github:
    repo: DelphosCloud/delphos-works
    branch: main
  run_command: python app.py
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /