name: delphos-works
functions:
- name: generate-document
  source_dir: functions/generate-document
  github:
    repo: https://github.com/DelphosCloud/delphos-works.git
    branch: main
  routes:
  - path: /api/generate
  environment_slug: python
  
- name: download-file
  source_dir: functions/download-file
  github:
    repo: https://github.com/DelphosCloud/delphos-works.git
    branch: main
  routes:
  - path: /api/download
  environment_slug: python

envs:
- key: SPACES_ENDPOINT
  value: lon1.digitaloceanspaces.com
- key: SPACES_BUCKET
  value: delphos-works